# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 03:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atlas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('x_size', models.IntegerField(default=0)),
                ('y_size', models.IntegerField(default=0)),
                ('z_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AtlasImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'/tfgWeb_atlas/')),
                ('pos_z', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'/tfgWeb_images/')),
                ('pos_z', models.IntegerField(default=-1)),
                ('time', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('x_size', models.IntegerField(default=0)),
                ('y_size', models.IntegerField(default=0)),
                ('z_size', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MuestraAtlas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('x_size', models.IntegerField(default=0)),
                ('y_size', models.IntegerField(default=0)),
                ('z_size', models.IntegerField(default=0)),
                ('atlas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgWeb.Atlas')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('reduce_factor', models.IntegerField(default=1)),
                ('total_times', models.IntegerField(default=0)),
                ('x_size', models.IntegerField(default=0)),
                ('y_size', models.IntegerField(default=0)),
                ('z_size', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, default='none', max_length=20)),
                ('username', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='muestra',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgWeb.Serie'),
        ),
        migrations.AddField(
            model_name='image',
            name='muestra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfgWeb.Muestra'),
        ),
        migrations.AddField(
            model_name='atlasimage',
            name='muestra',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tfgWeb.MuestraAtlas'),
        ),
    ]
